# language: generic if fails on rakefile not found
services: 
  - docker

before_install:
  - docker build -t gavsum/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true gavsum/react-test npm test

after_success:
  - docker build -t gavsum/multi-client ./client
  - docker build -t gavsum/multi-nginx ./nginx
  - docker build -t gavsum/multi-server ./server
  - docker build -t gavsum/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push gavsum/multi-client
  - docker push gavsum/multi-nginx
  - docker push gavsum/multi-server
  - docker push gavsum/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env-1
  bucket_name: elasticbeanstalk-us-east-1-351669524174
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
